CREATE OR REPLACE package GVERDE as
-------Author: Fabiana Chericoni--------------
    PROCEDURE CERCACROCIERE;
    PROCEDURE VISUALIZZACROCIERE(DATAPARTENZA VARCHAR2 DEFAULT NULL, PORTO PORTO.NOMEPORTO%TYPE);
    PROCEDURE APRIPAGINAPRENOTAZIONI(IDCR CROCIERA.IDCROCIERA%TYPE,IDNAVE NAVE.IDNAVE%TYPE, NTOUR TOUR.NOMETOUR%TYPE, DATAC varchar2 default null);
    PROCEDURE PAGAMENTO(IDNAVE NAVE.IDNAVE%TYPE,IDCR CROCIERA.IDCROCIERA%TYPE, PERSONE INT DEFAULT 0, SINGOLA TIPOCAMERA.TIPOLOGIA%TYPE, DOPPIA TIPOCAMERA.TIPOLOGIA%TYPE, TRIPLA TIPOCAMERA.TIPOLOGIA%TYPE);
    PROCEDURE INSERIMENTOPRENOTAZIONE(IDCROCIERA CROCIERA.IDCROCIERA%TYPE, COSTOBASE PRENOTAZIONE.COSTOBASE%TYPE, QUANTITASALDATA PRENOTAZIONE.QUANTITASALDATA%TYPE,PERSONE INTEGER,ACCONTO NUMBER,singola TIPOCAMERA.TIPOLOGIA%TYPE, doppia TIPOCAMERA.TIPOLOGIA%TYPE, tripla TIPOCAMERA.TIPOLOGIA%TYPE);
    PROCEDURE INSERISCICLIENTI(IDPRENOTAZIONE PRENOTAZIONE.IDPRENOTAZIONE%TYPE,PERSONE INTEGER, TOTALEPAGATO NUMBER);
    PROCEDURE CONTROLLOCLIENTE(CFISCALE be_UTENTE.CF%TYPE, NOME be_UTENTE.NOME%TYPE, COGNOME be_UTENTE.COGNOME%TYPE, TELEFONO NUMBER, EMAIL VARCHAR2, INFOPAG be_UTENTE.InformazioniPagamento%TYPE,IDPRENOTAZIONE PRENOTAZIONE.IDPRENOTAZIONE%TYPE,PERSONE INTEGER, TOTALEPAGATO NUMBER);    
    PROCEDURE INSERIMENTOCLIENTE(IDPRENOTAZIONE_P PRENOTAZIONE.IDPRENOTAZIONE%TYPE,IDCLIENTE INTEGER,PERSONE INTEGER, TOTALEPAGATO INTEGER);
    
    PROCEDURE MOSTRAPRENOTAZIONICLIENTE(TIPO INT DEFAULT 0,ELIMINA INT DEFAULT 0);
    PROCEDURE ELIMINAZIONEPRENOTAZIONE(IDPRENOTAZIONE_P PRENOTAZIONE.IDPRENOTAZIONE%TYPE, IDCLIENTE_P PRENOTAZIONE.IDCLIENTE%TYPE);

    PROCEDURE PAGINAPRENOTAZIONIVISITE(IDPRENOTAZIONE PRENOTAZIONE.IDPRENOTAZIONE%TYPE, IDVISITA VISITAGUIDATA.IDVISITA%TYPE, NOMEVISITA VISITAGUIDATA.NOMEVISITA%TYPE, DATAVISITA VARCHAR2 DEFAULT '', COSTOVISITA VISITAGUIDATA.COSTOVISITA%TYPE);
    PROCEDURE INSERIMENTOVISITA(COSTOTOTALE NUMBER DEFAULT 0, ACCONTO NUMBER DEFAULT 0, LINGUA GESTISCE.LINGUA%TYPE, IDPRENOTAZIONE PRENOTAZIONE.IDPRENOTAZIONE%TYPE, IDVISITA VISITAGUIDATA.IDVISITA%TYPE, COSTOUNITARIO VISITAGUIDATA.COSTOVISITA%TYPE);
    PROCEDURE FORMPAGAMENTOVISITE(TITOLO VARCHAR2 DEFAULT '',IDPRENOTAZIONE PRENOTAZIONE.IDPRENOTAZIONE%TYPE, IDVISITA VISITAGUIDATA.IDVISITA%TYPE, NOMEVISITA VISITAGUIDATA.NOMEVISITA%TYPE, DATAVISITA VARCHAR2 DEFAULT '', COSTOVISITA VISITAGUIDATA.COSTOVISITA%TYPE);

    PROCEDURE VISUALIZZAVISITE(IDPRENOTAZIONE_P PRENOTAZIONE.IDPRENOTAZIONE%TYPE, IDCLIENTE PRENOTAZIONE.IDCLIENTE%TYPE, IDC CROCIERA.IDCROCIERA%TYPE, ELIMINA INT DEFAULT 0);
    PROCEDURE ELIMINAZIONEVISITA(IDPRENOTAZIONE_P PRENOTAZIONE.IDPRENOTAZIONE%TYPE, IDVISITA_P VISITAGUIDATA.IDVISITA%TYPE);

    PROCEDURE PERCENTUALEVOTAZIONE;
    PROCEDURE CLIENTENOPRENOTAZIONEVISITE;
    PROCEDURE PRENOTAZIONIPERCROCIERA;
    PROCEDURE CROCIERACOSTOBASEMAGGIORE;

-------Author: Samuele Boldrini---------------

    procedure RECENSIONIGUIDA;
    procedure VISUALIZZARECENSIONIGUIDA(visita VISITAGUIDATA.IDVISITA%TYPE);
    
    procedure VOTOVISITA;
    procedure VISUALIZZAVOTOVISITA(visita VISITAGUIDATA.IDVISITA%TYPE);
    procedure VISUALIZZAVOTITUTTI;
    
    procedure PRENOTAZIONIVISITA;
    procedure VISUALIZZAPRENOTAZIONIVISITA(visita visitaguidata.idvisita%TYPE);
    procedure VISUALIZZAPRENOTAZIONITUTTE;
    
    procedure VISUALIZZARICHIESTECAMERE;

    PROCEDURE MOSTRARECENSIONI;
    PROCEDURE RECENSISCIVISITA;
    PROCEDURE SELEZIONAVOTO(visita NUMBER, imbarco NUMBER, aggiorna VARCHAR2);
    PROCEDURE INSERISCIRECENSIONE(visita NUMBER, imbarco NUMBER, voto_i NUMBER);
    PROCEDURE AGGIORNARECENSIONE(visita NUMBER, imbarco NUMBER, voto_i NUMBER);
    PROCEDURE ELIMINARECENSIONE(visita NUMBER, imbarco NUMBER);
    
    PROCEDURE NUMEROPRENOTAZIONICROCIERE;

    PROCEDURE NUMEROPRENOTAZIONICLIENTI;

    PROCEDURE PERCENTPRENOTAZIONIFINALI;

end;
