create or REPLACE view distanzaporti as
select p.POSGEOGRAFICA as POSGEOGRAFICAPORTO, p.NOMEPORTO, r.DISTANZA, l.POSGEOGRAFICA as POSGEOGRAFICALOCALITA, l.NOMELOCALITA
from porto P
    inner join RAGGIUNGE r on r.POSGEOGRAFICAPORTO = p.POSGEOGRAFICA
    inner join LOCALITA l on r.POSGEOGRAFICALOCALITA = l.POSGEOGRAFICA;

CREATE OR REPLACE VIEW PORTIPARTENZA AS 
  SELECT p.NOMEPORTO
from INCLUDE i
    join porto p on i.POSGEOGRAFICA = p.POSGEOGRAFICA
    join tour t on t.IDTOUR = i.IDTOUR
where i.ORDINE = 1;

CREATE OR REPLACE  VIEW COUNTLUOGHI AS 
  select li.NOMELUOGOINTERESSE, count(lv.IDVISITA) as conteggio
    from LUOGOVISITA lv join LUOGOINTERESSE li using (IDLUOGOINTERESSE)
    group by li.NOMELUOGOINTERESSE;

CREATE OR REPLACE VIEW VISITEPERLOCALITA AS 
  SELECT lc.POSGEOGRAFICA as POSGEOGRAFICA,
    lc.NOMELOCALITA as NOMELOCALITA,
    li.IDLUOGOINTERESSE as IDLUOGOINTERESSE,
    li.NOMELUOGOINTERESSE as NOMELUOGOINTERESSE,
    vg.IDVISITA as IDVISITA,
    vg.NOMEVISITA as NOMEVISITA,
    vg.COSTOVISITA AS COSTOVISITA
from localita lc
    inner join LUOGOINTERESSE li on lc.POSGEOGRAFICA = li.POSGEOGRAFICA
    inner join LUOGOVISITA lv on lv.IDLUOGOINTERESSE = li.IDLUOGOINTERESSE
    inner join VISITAGUIDATA vg on vg.IDVISITA = lv.IDVISITA;

create or replace view prenotazioneivisite AS
  select vg.IDVISITA, vg.NOMEVISITA, vg.COSTOVISITA
  from VISITAGUIDATA vg 
    inner join PRENOTAZIONEVISITA pv on pv.IDVISITA = vg.IDVISITA;

create or REPLACE view guidevisite as
SELECT IDVISITA, count( DISTINCT g.LINGUA) as numero_lingue
from VISITAGUIDATA vg 
    inner join GESTISCE g using (IDVISITA)
group by IDVISITA;
