create or replace package GUI as
	PROCEDURE APRIPAGINASTANDARD(TITOLO VARCHAR2 DEFAULT 'ISBD Crociere',LOAD VARCHAR2 DEFAULT '', MESSAGGIO VARCHAR2 DEFAULT '');
    procedure CHIUDIPAGINASTANDARD(footer varchar default 'Interfacce');
    procedure APRIHOMEPAGE;
    procedure APRIPAGINALOGIN;
    procedure HOMEPAGELOGIN;
	procedure APRINAV;
    procedure FORMCERCA;
    procedure FORMLOGIN;
    procedure FORMGRUPPI;
    
    PROCEDURE P(TESTO VARCHAR2 DEFAULT '',ID VARCHAR2 DEFAULT '');
    PROCEDURE CHIUDIDIV;
    PROCEDURE APRIDIV(CLASSE VARCHAR2 DEFAULT '');
    PROCEDURE APRIFORM(CLASSE VARCHAR2 DEFAULT 'FORM CARD', METODO VARCHAR2 DEFAULT '',AZIONE VARCHAR DEFAULT '',JS VARCHAR2 DEFAULT NULL);
    PROCEDURE CARDHEADER(TITOLO varchar2 default 'ISBD CROCIERE',LOGO INT DEFAULT 0);
    PROCEDURE HEADER(TITOLO VARCHAR2 DEFAULT '');
    PROCEDURE CHIUDIFORM;
    PROCEDURE APRIFIELD (CLASSE VARCHAR2 DEFAULT 'FIELD',TESTO VARCHAR2 DEFAULT '', ALLINEAMENTO VARCHAR2 DEFAULT '');
    PROCEDURE CHIUDIFIELD;
    PROCEDURE APRISELECTINPUT(NOME VARCHAR2 DEFAULT 'NAME', ID VARCHAR2 DEFAULT '',ONCHANGE VARCHAR2 DEFAULT '');
    PROCEDURE CHIUDISELECT;
    PROCEDURE OPTION_SELECT(VALORE VARCHAR2 DEFAULT '',TESTO VARCHAR2 DEFAULT '');
    PROCEDURE INPUT_FORM(CLASSE VARCHAR2 DEFAULT 'INPUT',TIPO VARCHAR2 DEFAULT 'TEXT',ID VARCHAR2 DEFAULT '', NOME VARCHAR2 DEFAULT '',VALORE VARCHAR2 DEFAULT '',PLACEHOLDER VARCHAR2 DEFAULT '', REQUIRED VARCHAR2 DEFAULT '', DISABLED VARCHAR2 DEFAULT '');
    PROCEDURE APRILABEL(CLASSE VARCHAR2 DEFAULT '',TESTO VARCHAR2 DEFAULT '');
    PROCEDURE CHIUDILABEL;

    PROCEDURE APRICONTAINER(LOAD VARCHAR2 DEFAULT '');
    PROCEDURE CHIUDICONTAINER;
    PROCEDURE FOOTER(creatore varchar default 'Interfacce');
    ------PROCEDURE TEXTBOX(label varchar2, placeholder varchar2);
    PROCEDURE BTN(CLASSE VARCHAR2 DEFAULT 'BTN',id varchar2 default '',nome varchar2 default 'btn',VALORE VARCHAR2 DEFAULT '', TXT varchar2 default 'button standard', ONSUBMIT VARCHAR2 DEFAULT '',CONFERMA INT DEFAULT 0);
    PROCEDURE BTNG(id varchar2 default '',nome varchar2 default 'btn', txt varchar2 default 'button standard');
    PROCEDURE BTNRESET(id varchar2 default '',nome varchar2 default 'reset', txt varchar2 default 'Cancella dati immessi');
    PROCEDURE BTNSUBMIT(nome varchar2 default 'submit', id varchar2 default '',TXT varchar2 default 'Invia',ALERT INTEGER DEFAULT 0, MESSAGGIO VARCHAR2 DEFAULT 'CIAO');
    
    PROCEDURE APRITABELLA(titolo VARCHAR2 default '', dimTitolo int default 1, attributi varchar2 default '', tableId VARCHAR2 default 't00');
    PROCEDURE CHIUDITABELLA;
    PROCEDURE APRIRIGATABELLA(attributi VARCHAR2 default '');
    PROCEDURE CHIUDIRIGATABELLA;
    PROCEDURE CELLATABELLA(val varchar2 default '', attributi varchar2 default '');
    PROCEDURE CELLATABELLAHEADER(val varchar2 default '', scopo varchar default 'col', attributi varchar2 default '');
    PROCEDURE CELLATABELLALINK(TXT VARCHAR2 DEFAULT '', ATTRIBUTI VARCHAR2 DEFAULT '', LINKTO VARCHAR2 DEFAULT '');
    PROCEDURE CELLATABELLABTN(TXT VARCHAR2 DEFAULT '', ATTRIBUTI VARCHAR2 DEFAULT '',LINKTO VARCHAR2 DEFAULT '',ONSUBMIT VARCHAR2 DEFAULT '', CONFERMA INTEGER DEFAULT 0);
    PROCEDURE APRIBTNTENDINA(nome VARCHAR2 default 'DROPDOWN', colore varchar default '');
    PROCEDURE CHIUDIBTNTENDINA;
    PROCEDURE AGGIUNGICAMPOTENDINA(nome VARCHAR2 default 'LINK',url VARCHAR2 default '');
    PROCEDURE VISUALIZZARISULTATIRICERCA(porto varchar2 default null, quando varchar2 default null);
    
    PROCEDURE MESSIMPORTANTE(TESTO VARCHAR2 DEFAULT '',LINKTO VARCHAR2 DEFAULT '');
    PROCEDURE APRICARD(INTESTAZIONE VARCHAR2 DEFAULT '',CLASSEHEADER varchar2 DEFAULT 'card1-header');
    PROCEDURE CHIUDICARD(FOOTER VARCHAR2 DEFAULT '');
    PROCEDURE CORPOCARD;
    PROCEDURE ESITOPERAZIONE(ESITO varchar2, MESSAGGIO varchar2 DEFAULT '',BTN VARCHAR2 DEFAULT 'NO',LINKTO VARCHAR2 DEFAULT '',TESTOBTN VARCHAR2 DEFAULT ''); 
    


end GUI;