
-- @Author : Andrea ferrari Luca Borrello

drop SEQUENCE IDTourseq;
drop SEQUENCE IDGuidaseq;
drop SEQUENCE IDCrocieraseq;
drop SEQUENCE IDLuogoInteresseseq;
drop SEQUENCE IDVisitaseq;
drop SEQUENCE IDNaveseq;
drop SEQUENCE IDCameraseq;
drop SEQUENCE IDPrenotazioneseq;
drop SEQUENCE IDImbarcoseq;

CREATE SEQUENCE IDTourseq
  MINVALUE 1
  START WITH 13
  INCREMENT BY 1;

CREATE SEQUENCE IDGuidaseq
  MINVALUE 1
  START WITH 7
  INCREMENT BY 1;

CREATE SEQUENCE IDCrocieraseq
  MINVALUE 1
  START WITH 23
  INCREMENT BY 1;

CREATE SEQUENCE IDLuogoInteresseseq
  MINVALUE 1
  START WITH 41
  INCREMENT BY 1;

CREATE SEQUENCE IDVisitaseq
  MINVALUE 1
  START WITH 26
  INCREMENT BY 1;

CREATE SEQUENCE IDNaveseq
  MINVALUE 1
  START WITH 6
  INCREMENT BY 1;

CREATE SEQUENCE IDCameraseq
  MINVALUE 1
  START WITH 58
  INCREMENT BY 1;

CREATE SEQUENCE IDPrenotazioneseq
  MINVALUE 1
  START WITH 6
  INCREMENT BY 1;

CREATE SEQUENCE IDImbarcoseq
  MINVALUE 1
  START WITH 5
  INCREMENT BY 1;


-- @Author : Gabriele

DROP SEQUENCE IDSESSIONE_SEQ;
DROP SEQUENCE IDUTENTE_SEQ;
DROP SEQUENCE IDEMAIL_SEQ;
DROP SEQUENCE IDRUOLO_SEQ;
DROP SEQUENCE IDPERMESSO_SEQ;

CREATE SEQUENCE IDSESSIONE_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 4294967295 CYCLE;
CREATE SEQUENCE IDUTENTE_SEQ START WITH 14 INCREMENT BY 1 MAXVALUE 4294967295 CYCLE;
CREATE SEQUENCE IDEMAIL_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 4294967295 CYCLE;
CREATE SEQUENCE IDRUOLO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 4294967295 CYCLE;
CREATE SEQUENCE IDPERMESSO_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 4294967295 CYCLE;
