--@Author Luca Borrello

CREATE OR REPLACE VIEW N_VISITECROCIERE AS
    SELECT
        CR.IDCROCIERA,
        COUNT(*) AS NUMERO_VISITE
    FROM
        CROCIERA CR,
        VISITEDISPONIBILI VD
    WHERE
        CR.IDCROCIERA=VD.IDCROCIERA
    GROUP BY
        CR.IDCROCIERA
    ORDER BY
        NUMERO_VISITE DESC;